spring.application.name=demo

#Database
spring.datasource.url=jdbc:mariadb://localhost:3306/shop?createDatabaseIfNotExist=true
spring.datasource.username = root
spring.datasource.password = fms2026
spring.datasource.driver-class-name = org.mariadb.jdbc.Driver

#Jpa-Hibernate
spring.jpa.show-sql = false
spring.jpa.hibernate.ddl-auto = update

#Cache
spring.thymeleaf.cache= false